### PR TITLE
Update hidden dependencies & bump to Python 3.9

### PR DESCRIPTION
**Pull request by Daltz333**
Pillow requires Python >3.7, I went ahead and bumped up to 3.8 since that's what we build with on everything.

### CODE REVIEW

**Comment by sciencewhiz** [comment]
There's several things in CI that are run with 3.7, should those get bumped to 3.8 also?

**Comment by TheTripleV** [comment]
Pillow dropped 3.6 but still supports 3.7. We could keep 3.7 until it EOLs next June.

We should also bump explicit dependencies (Sphinx mainly). The docs can't be build on 3.10 right now.

**Comment by Daltz333** [comment]
I don't like bumping the explicit dependencies mid season, besides just a minor version. The 3.10 bump I believe comes with a major version bump.

**Comment by Daltz333** [comment]
Okay, Python 3.10 does require a major Sphinx bump (4.3.0). I will otherwise bump to 3.9 (that's what comes with the Python in the Windows store) and bump the CI.

**Comment by Daltz333** [comment]
@sciencewhiz I have updated to Python 3.9 (not 3.10 as Sphinx is incompatible without updating to >=4.3.0). Additionally, the CI scripts and build instructions have been updated.

**Review by TheTripleV — APPROVED** [review]

**Pull request merged**
