### PR TITLE
Recreates diagrams in GraphViz

### LINKED ISSUE #220: Inconsistent Charts and Graphs
The documentation uses various different styles of diagrams, often changing on the same page. For example, [`What is “command-based” programming?`](https://frc-docs.readthedocs.io/en/latest/docs/software/commandbased/what-is-command-based.html) contains two largely different styles of diagrams, [this](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/software/commandbased/images/commandgroupchart.png), and [this](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/software/commandbased/images/commandflowchart.png).

This project already uses [graphviz](https://github.com/wpilibsuite/frc-docs/blob/f0cfb6b88e6fd1b08f953929eea0d33dd74e9100/source/docs/software/basic-programming/git-getting-started.rst#L147), but only in that one location. I will create a PR to remedy this.

### PR DESCRIPTION
**Pull request by Modelmat**
Fixes #220 

Thoughts on:
- ~~SVG output rather than PNG?~~ Browser support & labview metadata
- Using transparent (not white) backgrounds

Checklist:
- [x] [Types of Sensors](https://frc-docs.readthedocs.io/en/latest/docs/software/sensors/sensor-overview-software.html)
	The graph does not look exactly the same but it's as close as I could make it.
image
- [ ] [Vision Workflows](https://frc-docs.readthedocs.io/en/latest/docs/software/vision-processing/introduction/strategies-for-vision-programming.html)
    GraphViz doesn't seem to render this very nicely - https://gist.github.com/Modelmat/f9d9aa40af391e6a6c6b09c7bd4d3523
- [x] [Sources and Sinks](https://frc-docs.readthedocs.io/en/latest/docs/software/vision-processing/introduction/cameraserver-class.html)
	Done before this PR
- [x] [Subsystems and Commands](https://frc-docs.readthedocs.io/en/latest/docs/software/commandbased/what-is-command-based.html#id2)
image
- [x] [Scheduler Control Flow Diagram](https://frc-docs.readthedocs.io/en/latest/docs/software/commandbased/what-is-command-based.html#id3)
	This requires a complete remake (inaccurate). ~~Waiting on #191~~ ~~Done through #191~~ ~~Slight issues with existing; the end should instead draw an arrow back up to the start.~~ Complete
- [x] [Command Group with Concurrency](https://frc-docs.readthedocs.io/en/latest/docs/software/commandbased/command-groups.html#id4)
image
- [x] [NAT](https://frc-docs.readthedocs.io/en/latest/docs/networking/networking-introduction/networking-basics.html#public-vs-private-ip-addresses)
image

### CODE REVIEW

**Comment by AustinShalit** [comment]
image

Seems like the layout optimization might need to be fixed.

**Comment by Modelmat** [comment]
> image
> 
> Seems like the layout optimization might need to be fixed.

Yup, I'm working on it. I've got this at the moment:
image

**Comment by Modelmat** [comment]
I've been trying to work on the Vision Workflows diagram.
Current the version there is much more readable than what I've been able to make with GraphViz.
https://gist.github.com/Modelmat/f9d9aa40af391e6a6c6b09c7bd4d3523
Thoughts?

**Comment by Modelmat** [comment]
Not sure why the LinkCheck is failing? @Daltz333 
It works locally on my machine.

I'm marking this as "ready for review" now as the command scheduler seems to be done now.

The other remaining item, "Vision Workflows" does not seem to be readable with GraphViz, and may have to be recreated when we (maybe) migrate to draw.io

**Comment by AustinShalit** [comment]
The link check thing is not your fault. first.wpi.edu is unhappy with the link checker is all.

**Comment by Modelmat** [comment]
@Oblarg review?

**Comment by Daltz333** [comment]
Superceded by #620

**Pull request closed without merging**
