### PR TITLE
Add instructions to build an NT Client with Gradle

### LINKED ISSUE #516: Adding NetworkTables to a non-robot gradle project
This question is brought up quite a lot.

### PR DESCRIPTION
**Pull request by prateekma**
Also update links to 2020.2.2.
Closes #516

### CODE REVIEW

**Comment by ThadHouse** [comment]
The maven url here is wrong. It needs to point to the release repo.

**Comment by prateekma** [comment]
How do I do that?

**Comment by AustinShalit** [comment]
Replace the version numbers with `VERSION` and add a sentence about filling in the version number.

**Comment by prateekma** [comment]
Ah okay, simple enough; thought I had to do something with automatic Gradle versioning.

**Comment by AustinShalit** [comment]
you can probably just remove the version numbers from the links too. Users will be directed to a page listing the version numbers.

**Comment by prateekma** [comment]
@AustinShalit Anything else I need to change/add?

**Pull request merged**
