### PR TITLE
Fix NT Desktop Example

### LINKED ISSUE #1575: NetworkTables Listening For Value Changes Incorrect Variable Names
1. The two uses of variables named "table" are different and must be called different names.
```Java
table.addEntryListener("X", (table, key, entry, value, flags) -> {
               System.out.println("X changed value: " + value.getValue());
```
2. The return variable named "event" is subsequently incorrectly referenced as "value" which should have been called "event". (Oh the tyranny of copy/paste!)
```Java
yEntry.addListener(event -> {
               System.out.println("Y changed value: " + value.getValue());
```

### PR DESCRIPTION
**Pull request by Daltz333**
Close #1575

### CODE REVIEW

**Comment by jasondaming** [comment]
I think in the first paragraph of this article each mention of "Driver Station" (3 of them) should be "Driver Station computer".  I think this will help reduce confusion between the computer and a different program on it and the actual FRC Driver Station program.

**Comment by Daltz333** [comment]
That can be done in a separate PR.

**Comment by jasondaming** [comment]
I didn't understand this as being urgent.  I don't think it is big enough to warrant a separate PR.  It seems like our policy is when a document is changed we change all of it.

**Review by jasondaming — APPROVED** [review]

**Comment by Daltz333** [comment]
PRs are cheap. Refactoring a whole document has never been a policy when a change is done. Not since I had to fix all the garbage when I ran an autoconveter on the original markdown files.

**Pull request merged**
