### PR TITLE
Add REV Control System Overview

### PR DESCRIPTION
**Pull request by Daltz333**

### CODE REVIEW

**Comment by sciencewhiz** [comment]
Since ZTR doesn't cover the Rev components, should the diagram wait to be added until it does?

**Comment by Daltz333** [comment]
I do not see any harm in adding it now. I do not have a strong opinion and can remove it from the how-to-wire-a-robot page if you'd like, but it still can have a home in the control system hardware components page.

**Comment by sciencewhiz** [comment]
Yeah, that's what I was suggesting just remove it from ZTR not remove it entirely.

**Comment by Daltz333** [comment]
Sounds good

**Review by sciencewhiz — APPROVED** [review]

**Pull request merged**
