### PR TITLE
Add Inspector

### LINKED ISSUE #1292: Update RLIs
They are currently pinned to 2020 WPILib. They should be updated to the latest commit so #1075 can get merged to make this less painful in the future.

### PR DESCRIPTION
**Pull request by Starlight220**
fixes #1292 

This is the result of a simple `sed`. I'll try soon to write something to check if the code embeds are the same.

### CODE REVIEW

**Comment by Daltz333** [comment]
You can't actually replace the URLs. WPILib ran a full formatter, so the line numbers are also all wrong.

**Comment by Starlight220** [comment]
So I wrote something to test validity of RLIs, next up is adding auto-fixing capabilities.

<details>
  <summary>Current Output</summary>

### Up To Date

```
```

### Outdated
```
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1/wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp @ creating-benchtop-test-program-cpp-java.rst:197
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gettingstarted/Robot.java @ creating-benchtop-test-program-cpp-java.rst:189
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1/wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp @ creating-benchtop-test-program-cpp-java.rst:174
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gettingstarted/Robot.java @ creating-benchtop-test-program-cpp-java.rst:166
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gettingstarted/Robot.java @ creating-benchtop-test-program-cpp-java.rst:141
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1/wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp @ creating-benchtop-test-program-cpp-java.rst:98
```

### Invalid - Manual Intervention Needed
```
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1/wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp @ creating-benchtop-test-program-cpp-java.rst:149
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1/wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp @ creating-benchtop-test-program-cpp-java.rst:104
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gettingstarted/Robot.java @ creating-benchtop-test-program-cpp-java.rst:90
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1/wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp @ creating-benchtop-test-program-cpp-java.rst:75
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gettingstarted/Robot.java @ creating-benchtop-test-program-cpp-java.rst:67
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/ElevatorSimulation/cpp/Robot.cpp @ physics-sim.rst:93
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatorsimulation/Robot.java @ physics-sim.rst:85
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/ElevatorSimulation/cpp/Robot.cpp @ physics-sim.rst:71
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatorsimulation/Robot.java @ physics-sim.rst:63
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/ElevatorSimulation/cpp/Robot.cpp @ physics-sim.rst:51
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatorsimulation/Robot.java @ physics-sim.rst:43
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheel/cpp/Robot.cpp @ state-space-observers.rst:116
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheel/cpp/Robot.cpp @ state-space-observers.rst:110
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceflywheel/Robot.java @ state-space-observers.rst:102
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheel/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:248
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheelSysId/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:242
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceflywheel/Robot.java @ state-space-flywheel-walkthrough.rst:234
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheel/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:222
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheelSysId/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:216
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceflywheel/Robot.java @ state-space-flywheel-walkthrough.rst:208
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheel/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:193
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheelSysId/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:187
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceflywheel/Robot.java @ state-space-flywheel-walkthrough.rst:179
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheel/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:158
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheelSysId/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:152
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceflywheel/Robot.java @ state-space-flywheel-walkthrough.rst:144
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheel/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:120
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheelSysId/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:114
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceflywheel/Robot.java @ state-space-flywheel-walkthrough.rst:106
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheelSysId/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:85
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheelSysId/cpp/Robot.cpp @ state-space-flywheel-walkthrough.rst:79
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2021.1.1-beta-4/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceflywheelsysid/Robot.java @ state-space-flywheel-walkthrough.rst:71
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2020.3.2/wpilibcExamples/src/main/cpp/examples/AddressableLED/cpp/Robot.cpp @ addressable-leds.rst:147
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2020.3.2/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/addressableled/Robot.java @ addressable-leds.rst:139
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2020.3.2/wpilibcExamples/src/main/cpp/examples/AddressableLED/cpp/Robot.cpp @ addressable-leds.rst:127
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2020.3.2/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/addressableled/Robot.java @ addressable-leds.rst:119
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2020.3.2/wpilibcExamples/src/main/cpp/examples/AddressableLED/cpp/Robot.cpp @ addressable-leds.rst:34
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2020.3.2/wpilibcExamples/src/main/cpp/examples/AddressableLED/cpp/Robot.cpp @ addressable-leds.rst:28
- https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2020.3.2/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/addressableled/Robot.java @ addressable-leds.rst:20
```
</details>

**Comment by Starlight220** [comment]
\inspector fix all

**Comment by TheTripleV** [comment]
I really like the [output](https://github.com/Starlight220/frc-docs/pull/3#issuecomment-842681429) of this workflow. It is clear and descriptive. However, I think that the current method of execution, running on changed files in pull requests is incorrect. Files that are not updated often will be missed. New contributors' PRs might be blocked by unrelated errors. PRs will have unrelated changes tacked onto them (especially with squash and merge).
This tool should run on the entire repo at once and create an issue/pull request for manual/automatic changes. Think dependabot but for a specific use case.
Ideally, this workflow would run whenever allwpilib gets a new tag - allwpilib gets a new workflow that runs on tag and triggers this workflow in frc-docs.
If there is opposition to that level of integration, then this workflow could run as a daily check.

**Comment by Starlight220** [comment]
@Daltz333 While working on this I've seen that there are a *ton* of RLIs, and I think that it might be easier both for me and for your review to merge RLI fixes incrementally. Adding the Inspector action will be at the end after I've found and fixed any bugs that may be. What do you think?

**Comment by Starlight220** [comment]
I've cleaned up the impl a bit, tested everything. Before merge I'll bump the latest version variable in the `inspector.json` file to the latest allwpilib commit at the time. Currently, the trajectory tutorial is ignored; that can be changed in the `ignoredFiles` JSON variable.

Some technical details:
Two things can trigger an Inspector run:
- push to PR. This will run Inspector on the diff.
- Comments with commands will execute the command:
  - `\inspector check all` checks the whole repo instead of the diff.
  - `\inspector fix diff` commits the automatic fixes to the diff.
  - `\inspector fix all` commits the automatic fixes to everything.
- The workflow will comment once on the PR and then update that same comment when relevant. 
- Issues and PR comments without `\inspector` will create skipped workflows, not much to do about it.

---
Thoughts?

**Comment by Starlight220** [comment]
Workflow should change to run check-all on allwpilib tag (ie repository/workflow dispatch and a launching workflow in allwpilib) and create an issue, instead of check-diff.

check-all and fix-all commands remain.

@PeterJohnson @Daltz333 Did I miss something? Is there any point in keeping the check-diff functionality?

**Comment by Starlight220** [comment]
@Daltz333 assuming that the on-tag stuff will come in a separate PR, this is ready for review/merge

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
