### PR TITLE
Remove Background Gradient

### PR DESCRIPTION
**Pull request by Daltz333**
Due to popular request, removes the background gradient to focus on content, not have the background distract the reader.

### CODE REVIEW

**Comment by AustinShalit** [comment]
I do not like the default grey.  Can we leave it as a color?  Maybe the light blue that was the start of the gradient?


Screen Shot 2019-07-03 at 3 35 11 PM
Screen Shot 2019-07-03 at 3 35 16 PM

**Comment by AustinShalit** [comment]
Maybe it would look better if we used the grey somewhere else too, like under the logo area.

**Comment by AustinShalit** [comment]
Actually, maybe we should hold off on doing this because [frc-events](https://frc-events.firstinspires.org) uses a similar gradient. I think we want to have consistent styling.

**Comment by calcmogul** [comment]
Consistently bad style is still bad style. FIRST's own website doesn't even use this gradient; the colors are closer together chromatically on their site.

**Comment by AustinShalit** [comment]
The gradient is exactly the same as the one on the main site.

**Comment by calcmogul** [comment]
It's the same pattern, but it stretches across the whole page instead of just to the content. The brighter segments of it are covered by the page content whereas in rtd the gradient only stretches to the content, so the whole gammot of colors are shown. FIRST's website gradient looks better than RTD's because the brighter colors are hidden.

**Comment by Kevin-OConnor** [comment]
I would be fine with changing the gradient range so it looks more like what's on the FRC home page, but not getting rid of it.

**Comment by Daltz333** [comment]
I'm not inclined towards further modifying the design, this PR was only opened for public appeal anyways.

**Pull request closed without merging**
