### PR TITLE
Add unofficial resources

### LINKED ISSUE #1522: Update Support Resources to Include Other Support resources
Here is the current [page](https://docs.wpilib.org/en/latest/docs/software/support/support-resources.html)

Add rev documentation
Add Limelight docs / support
Add PhotonVision docs / support
Add unofficial support: CD & FRC Discord

### PR DESCRIPTION
**Pull request by Daltz333**
Close #1522 

I opted to not include documentation links, as that would be better fitted for an example page. Vendors are welcome to PR to this page and provide their own links.

### CODE REVIEW

**Comment by sciencewhiz** [comment]
Why would limelight be under unofficial support?

**Comment by Daltz333** [comment]
Why would limelight not?

**Comment by sciencewhiz** [comment]
What's the definition of unofficial vs official? Limelight is a company like rev and ctre.

**Comment by Daltz333** [comment]
I would say FIRST would have to make that distinction. I just went off of approved motor hardware vendors.

**Comment by Kevin-OConnor** [comment]
I agree with Joe that calling Limelight's official support "unofficial" seems a bit awkward. Perhaps an additional category for "Other Vendors" or similar? Limelight's official support and CD are pretty different types of resources.

**Comment by sciencewhiz** [comment]
Other vendors support:
https://www.kauailabs.com/support/navx-mxp/
https://www.playingwithfusion.com/contactus.php
copperforge is just an email address, but maybe we could link this: https://copperforge.cc/docs/software/libcu/

**Review by sciencewhiz — APPROVED** [review]

**Pull request merged**
