### PR TITLE
Add warning for C++ NPE

### PR DESCRIPTION
**Pull request by Oblarg**
Addresses https://github.com/wpilibsuite/frc-docs/issues/1147.

### CODE REVIEW

**Comment by Daltz333** [comment]
It was requested for an example of bad and how to fix it

**Comment by Oblarg** [comment]
I'm not quite sure how to easily structure a code example for this without it being fairly long - the setup is kind of obscure.  I can't just plop an excerpt from a command constructor in there - that's about as confusing as the description itself.

**Comment by Daltz333** [comment]
@Modelmat

**Comment by Modelmat** [comment]
I was thinking either a <details> element within the page (or just adding the actual example to a section at the bottom of the page).

Or perhaps just linking the the https://github.com/wpilibsuite/allwpilib/pull/3111 PR which fixed it within an example.

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
