### PR TITLE
Change images for ParallelCommandGroup and Subsystems and Commands

### PR DESCRIPTION
**Pull request by ItayZiv**
Changes the image for ParallelCommandGroup flow chat to represent the actual behavior, where the final command happens after both commands in the CommandGroup finishes, also changes the image for Subsystems and Commands in "What is "Command-Based" Programming?" to look similar.
Both images use the same format as the rest of the doc (Lato).

fixes: https://github.com/wpilibsuite/frc-docs/issues/263

Edit:
I used SVGs because vector graphics are most fitting for this type of image, not sure if PNG is preferred here.

### CODE REVIEW

**Comment by Daltz333** [comment]
Looks like PDF support is yelling about SVG. PNG should be fine in the meantime.

**Comment by calcmogul** [comment]
To include SVGs in my LaTeX book, I have to convert them to PDFs with inkscape, then use `\includegraphics{}` on the PDF files. I use `inkscape -D -z --file=filename.svg --export-pdf=filename.pdf` to convert them, with some makefile rules to generate it all for me.

**Comment by ItayZiv** [comment]
I changed the SVGs to quite high res PNGs, doesn't take a lot of space since its quite simple and should be good enough quality-wise, I'm still keeping the SVGs if they are needed at some point.

**Comment by ItayZiv** [comment]
Also, I noticed the old command-based docs has much more pictures explaining how stuff work than the new one, is it worth adding more images to the new command-based docs?

**Pull request closed without merging**
