### PR TITLE
Show pr changed files on rtd

### LINKED ISSUE #1275: Make changed pages easier to find in PR builds
For PRs, there should be a `What's New, Scooby Doo` page that contains a list of pages that were changed in the PR.

### PR DESCRIPTION
**Pull request by TheTripleV**
closes #1275.
after wpilibsuite/sphinxext-delta#3

### CODE REVIEW

**Comment by Daltz333** [comment]
I'm not sure how much we really want to bloat conf.py with non-sphinx themes? Could you extract this to its own python class with a function for this?

**Comment by TheTripleV** [comment]
Sure. We could throw that code into a new python file and just import it in.

I made changes to a few random pages as an example.
rst files changed in PRs show up at the bottom of the index and at the bottom of the sidebar.

**Comment by Daltz333** [comment]
Also, how do we differentiate from PR and regular builds?

**Comment by TheTripleV** [comment]
On pr builds, github_version is a commit hash instead of a branch name.

**Comment by Starlight220** [comment]
Is it possible to make the link from the CI build lead to the `Changed Files` page instead of the homepage?

**Comment by Daltz333** [comment]
No

**Comment by AustinShalit** [comment]
This is cool enough that others might benefit from it. Do you want to create a legit extension? (I don't care either way just tossing it out there).

**Comment by Daltz333** [comment]
We talked about it, and were a bit concerned on having too many sphinx extension repos (yes I know I'n against monorepos, but duplication sucks here)

If you see it having more usage, it can be made into a proper extension.

**Comment by AustinShalit** [comment]
Whatever y'all think I'll support you on.

**Comment by TheTripleV** [comment]
Replaced with sphinxext-delta.
CI should pass after it is available on PyPi.

**Review by Daltz333 — DISMISSED** [review]

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
