### PR TITLE
Fix typo in page title

### PR DESCRIPTION
**Pull request by sciencewhiz**

### CODE REVIEW

**Review by prateekma — APPROVED** [review]

**Comment by Daltz333** [comment]
Title underline is too short

**Comment by sciencewhiz** [comment]
The underline was too long, now its the right length

**Comment by Daltz333** [comment]
Looks like code linter is barfing on some files.

**Comment by sciencewhiz** [comment]
Yes, everything's broken until #1035 or another solution is merged

**Review by AustinShalit — APPROVED** [review]

**Pull request merged**
