### PR TITLE
Add presentation launcher

### PR DESCRIPTION
**Pull request by TheTripleV**

### CODE REVIEW

**Comment by Daltz333** [comment]
How do you exit presentation mode? ESC just gives a slide overview.

**Comment by TheTripleV** [comment]
The browser's back button. The presentation is considered to be a new webpage.

**Comment by Daltz333** [comment]
It might be worthwhile to make that more obvious, or have ESC go to the previous browser window instead and a different button open the tab overview.

**Comment by TheTripleV** [comment]
Ok. `ESC` now takes you back to the regular page. Turns out `o` also takes you to the overview.

**Comment by TheTripleV** [comment]
😮‍💨 It doesn't work on iOS. The js crashes on it.

**Comment by Daltz333** [comment]
It also crashes on Internet Explorer (don't actually care about this browser)

**Comment by Daltz333** [comment]
Pretty harmless so I don't see why we can't merge this.

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
