### PR TITLE
Update old command-based migration guide

### PR DESCRIPTION
**Pull request by Starlight220**

### CODE REVIEW

**Review by sciencewhiz — COMMENTED** [review]
I'm thinking the Trigger renames should be here too, since a team updating would need to deal with those also.

**Comment by Starlight220** [comment]
I doubt that the Trigger API didn't change for v2, and there isn't anything about it all in the doc.

**Comment by sciencewhiz** [comment]
Not specifically Trigger, but you don't really use commands without JoystickButton

**Review by Daltz333 — APPROVED** [review]
We should aim to remove this for 2024

**Pull request merged**
