### PR TITLE
Add feedforward intro

### PR DESCRIPTION
**Pull request by calcmogul**

### CODE REVIEW

**Comment by Oblarg** [comment]
I feel like this should be part of a separate section that is devoted purely to concepts, rather than to implementation.

**Comment by calcmogul** [comment]
Three small paragraphs doesn't really warrant a whole separate page.

**Comment by Oblarg** [comment]
There's more than can be said than those three small paragraphs, though, and it could be located in the same place as the conceptual PID docs.

**Comment by calcmogul** [comment]
That's all there is to say really, unless you want to get into plant inversion and a lot of other messy stuff.

**Comment by Oblarg** [comment]
It's worth going over the derivations for the models for common feedforwards, I think.

**Comment by AustinShalit** [comment]
@Oblarg Can you open an issue to add more information. I agree that this information is useful here.

**Pull request merged**
