### PR TITLE
Accept new articles

### PR DESCRIPTION
**Pull request by Daltz333**
Most of the screensteps have been ported. New articles are OK to be accepted, but revisions should be heavily preferred.

### CODE REVIEW

**Comment by ThadHouse** [comment]
This should state that any new content needs to be first approved before it can be accepted. Things like new sensors and other new info docs need to be approved first. Porting and corrections can be accepted without issue.

**Comment by Daltz333** [comment]
@ThadHouse. What would this approval process look like?

**Comment by ThadHouse** [comment]
Likely something on the PRs, but for the contributing doc likely say something like not everything can be accepted, and we will post a reason if not accepted, but no hard feelings if things get closed.

Sensors really are the big ones. Anything on the official docs needs to be on offically supported sensors.

**Comment by Daltz333** [comment]
@ThadHouse Is the above commit more appropriate?

**Pull request merged**
