### PR TITLE
Correct right motor inversion statement

### LINKED ISSUE #1571: Romi docs say right motor is inverted, it is not
The [Getting to know your Romi page](https://docs.wpilib.org/en/latest/docs/romi-robot/getting-to-know-romi.html) says:

> The right motor is hardwired to spin in a forward direction when forward stick movement is applied on a joystick. Thus there is no need to invert the corresponding motor controller in robot code.

This does not appear to be true. Before 2022 the `DifferentialDrive` class inverted the right motor controller automatically, so maybe this was a misunderstanding. With 2022 beta 4 I have found that the right motor controller needs to be inverted.

### PR DESCRIPTION
**Pull request by agasser**
Resolves #1571

### CODE REVIEW

**Comment by sciencewhiz** [comment]
This is subtly different then just inverting the previous statement, since forward on a joystick is negative.

Since I don't have a Romi, does sending the same value to both left and right motors cause it to spin in circles? Or is this about making sure forward and back are correct.

**Comment by agasser** [comment]
Sending the same output to both motors makes the Romi spin in circles. This statement is about motor inversion, but it does reference the joystick. In my PR I removed the reference to the joystick to avoid that additional confusion.

There is a separate statement about joystick inversion on the [Programming the Romi](https://docs.wpilib.org/en/latest/docs/romi-robot/programming-romi.html#running-a-romi-program) page.

**Comment by sciencewhiz** [comment]
The fact that the right side isn't inverted appears to be a bug in the Romi firmware. https://github.com/wpilibsuite/wpilib-ws-robot-romi/issues/115

**Comment by agasser** [comment]
> The fact that the right side isn't inverted appears to be a bug in the Romi firmware. [wpilibsuite/wpilib-ws-robot-romi#115](https://github.com/wpilibsuite/wpilib-ws-robot-romi/issues/115)

It is unexpected that one motor would be hardcoded to be inverted, but it's up to you maintainers to decide whether to change the docs or change the firmware.

**Review by Daltz333 — APPROVED** [review]

**Comment by Daltz333** [comment]
It has been discussed and determined that when both motors are given the same inputs, they should turn in opposing directions.

**Pull request merged**
