### PR TITLE
Revert "Update Inspector to v1.2 (#1939)"

### PR DESCRIPTION
**Pull request by sciencewhiz**
This reverts commit cb2e3baf1b44389580ef0a3fcceaa03f7b5bc90f.

### CODE REVIEW

**Comment by Starlight220** [comment]
Note that the version needs to be updated in the JSON.

**Comment by sciencewhiz** [comment]
It needs to be done as two steps since GH actions won't run the new stuff until merged.

**Comment by Starlight220** [comment]
Note that the old Inspector version will have all the deprecation warnings.

**Comment by sciencewhiz** [comment]
Yes, but the things deprecated don't get removed until mid next year

**Pull request merged**
