### PR TITLE
Remove software tools section

### PR DESCRIPTION
**Pull request by ItayZiv**
Remove software tools and split up the tools into the most fitting location. Not 100% sure about the locations...

fixes https://github.com/wpilibsuite/frc-docs/issues/505

### CODE REVIEW

**Comment by Daltz333** [comment]
Merge conflicts need to get fixed.

**Comment by ItayZiv** [comment]
I believe they are fixed now

**Comment by AustinShalit** [comment]
Approved. Because this is a restructure, I'd like to get another reviewer to make sure that this is the direction we want to move in. In general we try to avoid restructures but I think that in this case it makes sense.

@sciencewhiz

**Comment by ItayZiv** [comment]
Merged

**Comment by Daltz333** [comment]
@ItayZiv stale?

**Comment by Daltz333** [comment]
Closed as superceded

**Pull request closed without merging**
