### PR TITLE
Add SparkMax Color Codes

### PR DESCRIPTION
**Pull request by RishabRao**
Added sparkMax color codes

#297

### CODE REVIEW

**Comment by AustinShalit** [comment]
I think that this image does not convey the information as clearly as the image on screen steps.

**Comment by sciencewhiz** [comment]
How about using an animated gif so the blinking lights from Rev's website aren't lost? It would probably require a static png for pdf and the changes here: https://stackoverflow.com/questions/45969711/sphinx-doc-how-do-i-render-an-animated-gif-when-building-for-html-but-a-png-wh

**Comment by Daltz333** [comment]
It's been decided that MP4s are the best solution due to play/pause support. Unfortunately, we're trying to figure out where to store these outside of git.

**Comment by Starlight220** [comment]
Why is this marked with the `Waiting On: WPILib` label? What is it waiting on?

**Comment by Daltz333** [comment]
We are still deciding on how to handle animations, as we are worried about 
- Students with flashing sensitivity (so we need play/pause support that some browsers don't support gif with)
- LaTeX/PDF support
- Where do we store these large gif files?

**Comment by ItayZiv** [comment]
Are the gifs actually needed though? Wouldn't it be possible to just create a diagram showing the blink codes without actually needing the blinking?

**Comment by Daltz333** [comment]
I think if we could just create a tablet or vector image containing descriptions and a brief color (or color codes such as a line through yellow to represent flashing yellow) would be sufficient. If this PR wants to get updated to reflect that, or anyone else wants to take it on.

**Comment by Starlight220** [comment]
I might have the time to do this, but I'll probably need help with the format, etc.

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
