### PR TITLE
Ensure redirects.txt can only be appended to

### PR DESCRIPTION
**Pull request by TheTripleV**

### CODE REVIEW

**Comment by Daltz333** [comment]
Can you share a screenshot of this working?

**Comment by TheTripleV** [comment]
https://github.com/TheTripleV/frc-docs/pull/7, https://github.com/TheTripleV/frc-docs/pull/8, and https://github.com/TheTripleV/frc-docs/pull/9 are examples of this working. Modifying/deleting a line in redirects.txt fails the check.

**Comment by Daltz333** [comment]
Is it possible to give a more clear error message?

**Comment by TheTripleV** [comment]
It now errs with
> Error: redirects.txt can only be appended to. Lines cannot be modified or deleted.

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
