### PR TITLE
Fixed minor spelling/formatting/punctuation mistakes in AprilTag Intro, The Raspberry Pi pages

### LINKED ISSUE #2305: Few small spelling/formatting/punctuation mistakes in Vision Processing section
There are two spelling/punctuation mistakes I noticed while working on #2219:

- "What are AprilTags?": First bullet in "System Status" is not capitalized
- "The Raspberry Pi": A period is missing between sentences in paragraph 2

### PR DESCRIPTION
**Pull request by pjbuterbaugh**
Closes #2305.

### CODE REVIEW

**Comment by sciencewhiz** [comment]
This looks like your branch is based on stable instead of on main.

**Comment by pjbuterbaugh** [comment]
> This looks like your branch is based on stable instead of on main.

Working on this. Would a rebase be sufficient?

**Comment by sciencewhiz** [comment]
should be

**Comment by pjbuterbaugh** [comment]
> This looks like your branch is based on stable instead of on main.

Fixed as of [1a37af1](https://github.com/wpilibsuite/frc-docs/pull/2306/commits/1a37af1155e7056d8d4cddacd8d63263dc96bcb3).

**Comment by sciencewhiz** [comment]
Looks like it still has the change to zero to robot that it shouldn't have.

**Review by sciencewhiz — APPROVED** [review]

**Comment by sciencewhiz** [comment]
I did an interactive rebase to drop the extraneous commits

**Pull request merged**
