### PR TITLE
Update RLIs for 2022

### PR DESCRIPTION
**Pull request by Daltz333**
Fixes various RLIs for 2022.

### CODE REVIEW

**Comment by Daltz333** [comment]
Another round of RLI fixes for 2022. This batch is mostly inverting the right side in examples.

**Comment by sciencewhiz** [comment]
Are these changes in the 2022 alpha tag? That would probably be easier to find and update in the future.

**Comment by Daltz333** [comment]
Both are easily findable with a regex. I believe there are RLI breaking changes that have not been tagged yet.

**Comment by sciencewhiz** [comment]
My worry isn't searching for the commit id when the commit id is already known, but rather figuring out which commit id to search for.

**Comment by Daltz333** [comment]
Don't worry about the commit ID and use a regex with the prefix URL to help? I can update it to a tag, but there are RLIs that aren't tagged.

**Comment by Daltz333** [comment]
I have walked through all changed documents and verified that all changes RLIs are the functional equivalent and are accurate for the existing version of documents.

For change RLIs in the future to a pinned tag, a simple regex can be used to capture the group between ``/allwpilib/`` and ``/``. This PR is good for approval and merge.

**Review by jasondaming — APPROVED** [review]
Looks good thanks for all the work!

**Pull request merged**
