### PR TITLE
Add instructions for setting up CI with robot code

### LINKED ISSUE #57: Add documentation on how to set up AzureCI for CI builds
Low on the priority list, but it gets asked often enough it would be work doing as part of the simulation work.

### PR DESCRIPTION
**Pull request by prateekma**
Closes #57 

Here is the sample repository that I used to make sure these instructions work: https://github.com/prateekma/MyRobotProject

### CODE REVIEW

**Comment by AustinShalit** [comment]
Sweet. Can you open a PR to this repo too: https://github.com/wpilibsuite/Gearsbot

**Comment by ItayZiv** [comment]
If it’s added to gearsbot, remoteLiteralInclude should be possible as well.

**Comment by ItayZiv** [comment]
Also, it might be worth adding a note about grades build/check/test (and possibly this diagram from gradle’s user guide https://docs.gradle.org/current/userguide/img/javaPluginTasks.png , iirc the docs are CCv4)

**Comment by sciencewhiz** [comment]
Since we don't have any instructions for writing a unit test, I think that should be included as part of this too.

**Comment by prateekma** [comment]
I'm not sure if I would be qualified to write something for unit testing robot code. The only tests my team has done include testing general math/algorithm techniques and nothing related to the robot framework itself.

I think it would be better if someone else added that to a separate article within the same "Basic Programming" section.

**Comment by ItayZiv** [comment]
I personally think putting in in another PR might be fine just because of how much extra work it is, also might be more fit under advanced-controls

**Pull request merged**
