### PR TITLE
Make state-space Python scripts work with latest version of frccontrol

### PR DESCRIPTION
**Pull request by calcmogul**
Also give execute permissions to Python scripts. Images weren't
regenerated because the output looks identical.

### CODE REVIEW

**Comment by TheTripleV** [comment]
The versions of these dependencies should also be locked in vcs

**Comment by calcmogul** [comment]
They don't appear to be installed at all in CI. The image generation isn't automated.

**Comment by TheTripleV** [comment]
I think automating image generation is the way to go. Even without that, these should be locked so that the scripts won't magically stop working.

**Comment by calcmogul** [comment]
Locking them wouldn't do anything because currently, the scripts have to be run manually using whatever packages are installed locally.

**Comment by TheTripleV** [comment]
Locally, you're already supposed to use the deps specified via requirements.txt or poetry. So it would use the locked version.

**Comment by Daltz333** [comment]
Some of the bumped dependencies require Python 3.8. Can you double check that the contributing instructions have that listed as a minimum version, and if not, bump it?

**Comment by sciencewhiz** [comment]
Is the latest version of numpy actually required or could an older version be used to avoid bumping the python version?

**Comment by calcmogul** [comment]
It would take me a while to figure out what earlier versions of everything in the dependency chain are valid. For what it's worth, Python 3.8 had its first release almost three years ago, and Python 3.7 will be end-of-life in 11 months.

https://devguide.python.org/versions/#supported-versions

**Comment by calcmogul** [comment]
> Can you double check that the contributing instructions have that listed as a minimum version, and if not, bump it?

The minimum version in build-instructions.rst says the required version is Python 3.9 (and that 3.10 is incompatible).
```
frc-docs/build-instructions.rst
16:- `Python 3.9 <https://www.python.org/downloads/>`__ (Python >= 3.10 is incompatible)
```

**Comment by TheTripleV** [comment]
In pyproject.toml, the min python version is marked as 3.9 so poetry picks 3.9+ compatible dependencies. The behavior is correct

**Review by TheTripleV — APPROVED** [review]

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
