### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by Daltz333**
The below bullets highlight what I have deemed as "important" changes between the current dependency version, and the updated dependency versions.

- doc8
○ Compatibility fixes for newer python versions
○ Fix windows vs linux whitespace detection
- docutils
○ Large amounts of changes related to HTML generation. **Requires testing!!**
- fonttools
○ No noticable changes that affect us.
- sphinx
○ Large amounts of changes. **Requires testing!!**
- hoverxref
○ Stable instead of beta release.
○ Various javascript fixes
○ CORS related fix
- sphinx-notfound-page
○ Fix issues on Python >=3.10
○ Fix issues on Sphinx >=4.2
- sphinx-tabs
○ Bug fixes
- sphinx-ghcontributors
○ Changed the HTML generation for previewing contributors **Requires testing!!**
- sphinxcontrib-svg2pdfconverter
○ Bug fixes
○ Compatibility for newer python versions

### CODE REVIEW

**Comment by Daltz333** [comment]
Closes #1764

**Comment by Daltz333** [comment]
Confirmed testing on RTD. HTML generation poses no obvious problems. Tab functionality is preserved. Contributions has stayed the same as we have not opted into the new preview feature.

**Comment by TheTripleV** [comment]
Why did make.bat change?

**Comment by Daltz333** [comment]
Reenables D002 check on windows as it was fixed upstream

**Review by TheTripleV — APPROVED** [review]

**Pull request merged**
