### PR TITLE
Add alternative document URLs to the README

### PR DESCRIPTION
**Pull request by Daltz333**
Sometimes schools will wildcard block websites (like my old school blocking anything with "networking" in the URL 🤢). This adds the list of domains to the README, and states that the WPILib domain is the preferred domain.

### CODE REVIEW

**Comment by sciencewhiz** [comment]
Why is it prefered to use the wpilib.org domain? Does it matter at all?

**Comment by Daltz333** [comment]
It doesn't necessarily, just to maintain consistency.

**Pull request merged**
