### PR TITLE
Update RLIs for 2024 beta 2

### PR DESCRIPTION
**Pull request by sciencewhiz**
Ignore command scheduler since need updates to match the new code

### CODE REVIEW

**Comment by sciencewhiz** [comment]
\inspector fix all

**Comment by sciencewhiz** [comment]
\inspector check all

**Comment by sciencewhiz** [comment]
@Starlight220 inspector is crashing https://github.com/wpilibsuite/frc-docs/actions/runs/6520971385/job/17709084246#step:10:14

**Comment by Starlight220** [comment]
I'll take a look and try to fix it in the evening.

**Comment by sciencewhiz** [comment]
\inspector check all

**Comment by sciencewhiz** [comment]
\inspector check all

**Comment by sciencewhiz** [comment]
\inspector check all

**Comment by sciencewhiz** [comment]
\inspector check all

**Comment by sciencewhiz** [comment]
\inspector fix all

**Comment by Starlight220** [comment]
I think it's failing on one of the StandaloneApp RLIs.

**Comment by sciencewhiz** [comment]
\inspector fix all

**Comment by sciencewhiz** [comment]
\inspector check all

**Comment by sciencewhiz** [comment]
\inspector check all

**Comment by sciencewhiz** [comment]
\inspector fix all

**Comment by sciencewhiz** [comment]
\inspector check all

**Comment by sciencewhiz** [comment]
\inspector check all

**Comment by sciencewhiz** [comment]
\inspector check all

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
