### PR TITLE
Style similar to existing FIRST web assets

### PR DESCRIPTION
**Pull request by Kevin-OConnor**
This PR updates the page style to be similar to existing _FIRST_ web assets such as the firstinspires.org home page and frc-events.firstinspires.org. The goal is to blend that style with the typical RTD navigation style. This also updates the logo to a combined WPILib/WPI/FRC logo.
DocStyle

### CODE REVIEW

**Comment by Daltz333** [comment]
I love it.

**Comment by Daltz333** [comment]
@kevin-oconner I should've checked this but it breaks on mobile.

**Comment by Kevin-OConnor** [comment]
Oops! Just the Game Manual link right? Not sure how I lost the CSS rule to hide that one but I can PR a fix.

**Comment by Kevin-OConnor** [comment]
Actually, I'll just hide all three links with a single media rule. It looks like some of the other stuff I had been playing with was what made it look normal dropping them off one at a time as it shrunk.

**Pull request merged**
