### PR TITLE
Update RLIs for 2022-beta-4

### PR DESCRIPTION
**Pull request by Starlight220**

### CODE REVIEW

**Comment by Starlight220** [comment]
@Daltz333 what do you think? 18 files fixed with a single command.

**Comment by sciencewhiz** [comment]
Except it fixed them to beta 3, not beta 4

**Comment by Starlight220** [comment]
\inspector fix all

**Comment by Starlight220** [comment]
\inspector fix all

**Comment by Starlight220** [comment]
\inspector check all

**Comment by Starlight220** [comment]
\inspector check all

**Comment by Starlight220** [comment]
\inspector check all

**Comment by Starlight220** [comment]
\inspector check all

**Comment by Starlight220** [comment]
\inspector check all

**Comment by Starlight220** [comment]
All RLIs updated! 🎉

**Comment by sciencewhiz** [comment]
I'm surprised there aren't conflicts since #1581 was  merged

**Comment by Starlight220** [comment]
There aren't conflicts because the trajectory tutorial is ignored by Inspector. The ignore was added at a time where we thought that the trajectory tutorial was going to be rewritten, so there was no point in updating RLIs. Now that the RamseteCommand rewrite is stalled, there's a case for removing the ignore.

**Comment by Daltz333** [comment]
I took a brief look and everything seems okay. It's a huge amount to review, so we can open any issues for any RLIs that come up bad.

**Comment by sciencewhiz** [comment]
\inspector check all

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
