### PR TITLE
Expanding the Glossary

### PR DESCRIPTION
**Pull request by jasondaming**
Based on numerous CD threads there are a lot of acronyms used.  Wanted to expand this glossary to include them.

Thoughts on abbreviation structure?  We could instead list the term and then include the abbreviation in the description.

Do you think all of this should go into the glossary?  I have heard arguments about breaking it up.  To me a glossary is not really something you read it is instead something that is searched for to answer a specific need.  In this case the size is irrelevant but the completion only becomes more helpful with more entries.

### CODE REVIEW

**Comment by jasondaming** [comment]
@Kevin-OConnor I did make a few changes to ZTR figured I should tag you but it is really just correcting an abbreviation that was wrong.  PH->PDH

**Comment by sciencewhiz** [comment]
Seems like a good place to fix #2388

**Comment by sciencewhiz** [comment]
I like all the entries except EPA and OPR. Those seem to be getting too far away from the purpose of frc-docs

**Comment by jasondaming** [comment]
Fixes #2388 

I think EPA and OPR are used often enough in the FRC context to warrant inclusion.  I am not going to die on this hill however so am interested in what others think.

**Review by sciencewhiz — APPROVED** [review]

**Pull request merged**
