### PR TITLE
Add quote regarding asking for help

### PR DESCRIPTION
**Pull request by Daltz333**

### CODE REVIEW

**Comment by sciencewhiz** [comment]
While true, I'm not sure that this is helpful (in its current form). I think someone being lazy is a very uncommon reason why there's limited detail posted. I think not understanding what is relevant is much more common. Something like an FRC version of ESR's how to ask questions the smart way is what's really needed.

**Comment by Daltz333** [comment]
Is this the document you refer to? https://d.cxcore.net/Eric%20S%20Raymond/How%20To%20Ask%20Questions%20The%20Smart%20Way.pdf

**Comment by sciencewhiz** [comment]
yes

**Comment by jasondaming** [comment]
I also don't think "How to read Stacktraces" is the right document for this.  If you want to give advice on general seeking help I think that would be ideal in a [FAQ](https://github.com/wpilibsuite/frc-docs/issues/515) type document.  This already says "full text" and I can't even count how often we get only partial traces usually with the wrong info.

**Pull request closed without merging**
