### PR TITLE
Fix secret syntax; use bool literal

### PR DESCRIPTION
**Pull request by AustinShalit**

### CODE REVIEW

**Review by Daltz333 — APPROVED** [review]

**Comment by TheTripleV** [comment]
Would you also want to enable Push on workflow_dispatch? That way, a wpilib member manually triggering this workflow would make it publish to stable too.

**Comment by Daltz333** [comment]
That's already there

**Comment by AustinShalit** [comment]
This does not work.

**Comment by TheTripleV** [comment]
workflow_dispatch doesn't push to stable if secrets.PUBLISH_STABLE isn't set.

**Pull request merged**
