### PR TITLE
Remove duplicated images

### PR DESCRIPTION
**Pull request by katzuv**
#227 
I fixed all the duplicates shown in the issue.
However, I wanted to find all duplicated in the docs. So I used [this](https://www.pythoncentral.io/finding-duplicate-files-with-python/) Python script that finds duplicate files (not only images). It can get as arguments a folder or several folders.
Using [this](https://superuser.com/a/426004) Linux Terminal command I found all directories holding images in the `source` directory. The final command looked like this:
```bash
python3 dupFinder.py $(find . -path '*/images/*' -type d)
```
That showed there are actually more duplicates (8 of them to be exact).
Maybe this check should be added to the CI or something. Maybe even write a script to fix this automatically.

Anyway, here are my fixes.

### CODE REVIEW

**Comment by Modelmat** [comment]
I believe those extra duplicates were in different sections of the docs. I was told that moving them out would require placing them in some top-level assets directory which apparently is unwieldy.
(As opposed in the local images/) directory.

**Comment by katzuv** [comment]
> I believe those extra duplicates were in different sections of the docs.

Yes, you are right. Can you use relative imports in `.rst` files?

**Comment by Modelmat** [comment]
They are relative, unless prefixed with /, which corresponds to Sphinx's basedir (iirc).

I don't think it would be a good idea to use image files from other sections' image folder - this seems like a bad idea.

**Comment by katzuv** [comment]
Yeah, you're probably right about this.
So I think all the samd-folder duplicates were fixed, I'll double check it in the morning (it's already night here in Israel 🙃).

**Comment by katzuv** [comment]
OK, so I checked again, and these are all the needed fixes. Can someone review this PR?

**Comment by katzuv** [comment]
Thanks, @AustinShalit!

**Comment by AustinShalit** [comment]
Yup. Just waiting for @Daltz333 to confirm that this looks ok.

**Pull request merged**
