### PR TITLE
Update vscode-wpilib RLIs

### PR DESCRIPTION
**Pull request by sciencewhiz**

### CODE REVIEW

**Comment by sciencewhiz** [comment]
\inspector fix all

**Comment by sciencewhiz** [comment]
\inspector fix all

**Comment by sciencewhiz** [comment]
@Starlight220 any idea why this failed? Trying to update this: https://github.com/wpilibsuite/frc-docs/blob/main/source/docs/romi-robot/programming-romi.rst#running-a-romi-program

**Comment by Starlight220** [comment]
Apparently the regex Inspector uses internally to capture the resource filepath doesn't have a `-`, so it doesn't match `vscode-wpilib/resources/gradle/javaromi/build.gradle` etc. I'll open an issue on the Inspector repo.

**Comment by sciencewhiz** [comment]
Superseded by #2120

**Pull request closed without merging**
