### PR TITLE
Remove note about scaling on Retina displays

### PR DESCRIPTION
**Pull request by prateekma**
This was fixed in a recent allwpilib commit (https://github.com/wpilibsuite/allwpilib/pull/3135)

### CODE REVIEW

**Comment by prateekma** [comment]
@sciencewhiz This should be good to go now.

**Comment by Daltz333** [comment]
Should we wait until a release is cut?

**Comment by sciencewhiz** [comment]
I think so, since we don't have separate latest and stable right now.

**Review by Daltz333 — DISMISSED** [review]

**Comment by sciencewhiz** [comment]
Thinking about it some more, I think I would prefer to add something to say to update to 2021.2.2 or later, rather then deleting it.

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
