### PR TITLE
Update odometry advice to use relativeTo method

### PR DESCRIPTION
**Pull request by Oblarg**
Per previous discussion, this is better advice than resetting the odometry.

### CODE REVIEW

**Comment by prateekma** [comment]
A robot centric to field relative transformation should use the `transformBy` method, not the `relativeTo` method. Using `relativeTo` will cause all poses to be negative since the origin relative to any positive pose is a negative transform.

**Comment by Oblarg** [comment]
`transformBy` takes a `Transform2D` rather than a `Pose2D`, though; are they implicitly convertible?

**Comment by prateekma** [comment]
If the origin is at (0,0), then yes. Alternatively, you can pass in `robotPose.minus(startPoseOfRobotCentricTraj)` which automatically creates the transform.

**Comment by AustinShalit** [comment]
@prateekma This look good now?

**Comment by prateekma** [comment]
Yes

**Pull request merged**
