### PR TITLE
Add note about LQR gains being aggressive

### PR DESCRIPTION
**Pull request by calcmogul**
971's "Design for Controlability" presentation goes into a lot more detail on the points raised here. https://www.youtube.com/watch?v=VNfFn-gcfFI

### CODE REVIEW

**Comment by Oblarg** [comment]
Perhaps add "If the system cannot be made more rigid, the gains can always be lowered."

**Comment by sciencewhiz** [comment]
If you filter a sensor with agressive gains, isn't it even more likely to go unstable due to the phase delay?

**Comment by calcmogul** [comment]
Depends on what kind of filtering and how much.

**Comment by prateekma** [comment]
I think that lowering the gains will be the quickest and most effective way to reduce the aggressiveness of the LQR gains for most users -- so this suggestion should definitely be added as well.

**Comment by calcmogul** [comment]
An IIR filter with a fast pole does well. Kalman filters combine this with a model to help with phase delay, but Kalman filters my team has applied to fast, aggressive control loops generally trust the measurements much more than the model (it's just how the relative weights for the process noise vs measurement noise have worked out).

**Comment by sciencewhiz** [comment]
Is this superseded by #550>

**Comment by AustinShalit** [comment]
@calcmogul 

>Is this superseded by #550

**Comment by calcmogul** [comment]
Yes.

**Pull request closed without merging**
