### PR TITLE
Added Keyboard Shortcut for MacOS installation 

### PR DESCRIPTION
**Pull request by RishabRao**
added the cmd + shift + H shortcut to the finder tab to get to home. Makes it easier to get to home for less experienced users.

### CODE REVIEW

**Comment by sciencewhiz** [comment]
The way it's worded, it sounds like pressing cmd+shift+h will magically copy the stuff to the right folder.

**Comment by AustinShalit** [comment]
I would recommend teams use the Go menu in the menu bar rather than a shortcut.

**Comment by RishabRao** [comment]
> I would recommend teams use the Go menu in the menu bar rather than a shortcut.

I have seen instances of the home folder not showing up on the finder windows leading to confusion from programmers on my team. If the shortcut is also provided they have an alternative.

**Comment by AustinShalit** [comment]
Yup. Which is why I think the go menu will work the best.

**Comment by Daltz333** [comment]
@RishabRao any update on the addressed comments?

**Comment by Daltz333** [comment]
Closing as stale.

**Pull request closed without merging**
