### PR TITLE
Fix link syntax that was broken in #2690

### PR DESCRIPTION
**Pull request by sciencewhiz**

### CODE REVIEW

**Comment by TheTripleV** [comment]
`:ref:[CTRE Power Distribution Panel](docs/software/can-devices/power-distribution-module:Power Distribution Module)` is supposed to work. I'll take a look at the generation

**Comment by sciencewhiz** [comment]
It does work, but the only ones that were switched were the ones that were on the same line as an external link. This makes them all consistent again, so we can switch them all later.

**Review by TheTripleV — DISMISSED** [review]

**Comment by jasondaming** [comment]
I think we can do this if you resolve conflicts

**Comment by sciencewhiz** [comment]
I found more categories of issues I'm working on

**Comment by sciencewhiz** [comment]
Supersedes #2701

**Pull request merged**
