### PR TITLE
Update to sphinx 7

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
Currently first pass

### CODE REVIEW

**Comment by sciencewhiz** [comment]
Unfortunately, It's fairly common for things to break on big upgrades like this in the past.

Here's what I've noticed:

- colors on the front page panels shifted slightly (not necessarily a problem, but a possible indication of other CSS issues)s
- 404 page is all messed up
- sphinx-rtd-theme v2 (which looks to add support for Sphinx 7) should be released soon. Not sure what might be broken with the older version.

I'm not sure if there's a way to see if translations or pdf/html still works without merging @Daltz333

**Comment by Daltz333** [comment]
You can build translations locally to test, but I'd just rely on CI to test PDF builds.

**Comment by sciencewhiz** [comment]
Looks like translations failed

**Comment by sciencewhiz** [comment]
The colors on the front panels seem back to normal

**Comment by Daltz333** [comment]
Needs a rebase

**Comment by GrahamSH-LLK** [comment]
> Needs a rebase

Rebased and builds succeeding.

**Review by sciencewhiz — APPROVED** [review]

**Comment by GrahamSH-LLK** [comment]
@sciencewhiz Strange that it failed. I can repro the problem locally by running the command that rtd runs for whatever part of the build it is that failed. However, I can't figure out where the problem is as the stack trace is fairly unhelpful.

**Comment by sciencewhiz** [comment]
@TheTripleV identified the problem as being from https://github.com/wpilibsuite/frc-docs/blob/main/source/_extensions/rtd_patch.py

**Comment by TheTripleV** [comment]
Adding `*args, **kwargs` to both inits (definition and call) should make it work on current sphinx and sphinx 7.

**Comment by GrahamSH-LLK** [comment]
Fixed PR in #2395

**Pull request merged**
