### PR TITLE
Remove FRC CAN Device Specifications document

### PR DESCRIPTION
**Pull request by yellowjaguar5**
It appears that the FRC CAN Device Specifications document got stranded in the `hardware` directory, but its accompanying article now lives in `software/can-devices`. This PR links the document with its related article. 

Also, can the `frc-can-device-specifications` document just be deleted? The article with the same name seems to be a copy of it.

### CODE REVIEW

**Comment by Daltz333** [comment]
Honestly the PDF can just get deleted IMO, however this is more up to FIRST.

**Comment by Kevin-OConnor** [comment]
If the article has all of the info from the doc then the doc can go. It was posted to screensteps when we didnt have time to port the content from the word doc for something used so infrequently

**Comment by AustinShalit** [comment]
Do we need to remove the link too?

**Comment by yellowjaguar5** [comment]
I took the link out of the article because I removed the document if that's what you meant.

**Pull request merged**
