### PR TITLE
Use more modern command based examples for RLIs

### PR DESCRIPTION
**Pull request by Gold856**

### CODE REVIEW

**Review by jasondaming — CHANGES_REQUESTED** [review]
https://raw.githubusercontent.com/wpilibsuite/allwpilib/v2024.3.2/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/RapidReactCommandBot.java

Java Toggle on True seems to be using the wrong lines it just shows a bracket currently

**Comment by Gold856** [comment]
Fixed Java Toggle on True. The broken link is part of #2695.

**Comment by sciencewhiz** [comment]
I don't think the broken link on line 35 is related to #2695 since there's no parenthesis. The broken link on line 18 is, though.

**Comment by Gold856** [comment]
Yeah, line 35 is just broken. Not because of this PR though.

**Review by jasondaming — APPROVED** [review]

**Pull request merged**
