### PR TITLE
Update REV CS Image to use 10amp fuse for PH

### PR DESCRIPTION
**Pull request by Daltz333**

### CODE REVIEW

**Comment by TheTripleV** [comment]
Are the PDH, PH, and Radio Power Module meant to get darker?

**Comment by Daltz333** [comment]
Yeah, we were on the original version of the image and this is 2 versions ahead

**Review by TheTripleV — APPROVED** [review]

**Comment by NoahAndrews** [comment]
Why was this changed? Teams are supposed to use a 15A fuse there.

**Comment by Daltz333** [comment]
See discussion in WPILib slack. There was a messup in communications resulting from a mixture of bad information.

**Pull request merged**
