### PR TITLE
Image Filenames and Accessibility

### LINKED ISSUE #225: Image Filenames and Accessibility
Images should be renamed from `imageXX` to a meaningful name.
Alt text should also be added in the RST.

### PR DESCRIPTION
**Pull request by jasondaming**
Old

### CODE REVIEW

**Review by AustinShalit — COMMENTED** [review]
Thank you for this draft! I think the alt text is really important. What do you think about rephrasing the sentences so that they all do not start with a "showing" verb? For example: `Shows the project homepage and graphs.` could just be `The project homepage and graphs.`

**Comment by jasondaming** [comment]
Okay I think that is fine.  What do you think about highlights?  I think that brings value indicating that something on the image has been annotated (added a red box or whatever around it).

**Comment by Daltz333** [comment]
This PR is impossible to review, I'd advise you to create a new branch and cherry pick the necessary commits onto there

**Comment by jasondaming** [comment]
This touches virtually every file in docs...I don't know how it can be "easy" to review

**Comment by prateekma** [comment]
It's not easy to review because your branch isn't rebased properly: it shows changes from commits that have already been merged to master.

**Comment by jasondaming** [comment]
I would love to understand how to rebase a huge PR like this properly then!  Just following the prompts nothing special.

**Comment by jasondaming** [comment]
At this point however if I apparently screwed up something as simple as rebasing I don't want to do anything else new to it.

**Comment by prateekma** [comment]
I would recommend what Dalton said above -- cherry-pick the relevant commits into a new branch and create a new PR from that branch.

**Comment by jasondaming** [comment]
do I commit after one cherry-pick or do all the cherry-picks in one commit?

**Comment by prateekma** [comment]
When you cherry-pick a commit / a series of commits from one branch to another, it automatically copies the commits to the new branch; you don't have to use `git commit` manually again. https://git-scm.com/docs/git-cherry-pick

**Comment by jasondaming** [comment]
The cherry picking process makes me redo every single conflict.  Unless I am missing something this will take forever.

**Comment by Daltz333** [comment]
No, github says this touches literally every file including the css when it shouldn't

**Comment by Daltz333** [comment]
Yep...

**Comment by jasondaming** [comment]
working on a new repo

**Comment by jasondaming** [comment]
Closing in favor of PR #1209

**Pull request closed without merging**
