### PR TITLE
Advanced Controls Tuning Walkthrough Real-Time Plotting

### PR DESCRIPTION
**Pull request by gerth2**
Moved away from Highcharts to a more-performant zero-copy JS implementation.

Reworked all simulations to iteratively run and display the data

### CODE REVIEW

**Comment by gerth2** [comment]
https://user-images.githubusercontent.com/4583662/188497162-442bac96-3f0e-440e-b016-1016db719943.mp4

**Comment by Daltz333** [comment]
How does it look on mobile?

**Comment by gerth2** [comment]
image

Simulated in my browser. Will do some CI cleanups to get a publish and try it out on a real mobile device. I know I"m missing a few updates on resize (it'll overdraw the screen till you restart the sim...)

**Comment by sciencewhiz** [comment]
This no longer pegs a core on my browser

**Comment by gerth2** [comment]
Let me know any additional thoughts. I'm fairly happy at this point and I know a few folks have had their eyes on it already.

**Comment by gerth2** [comment]
For documentation: Will close https://github.com/wpilibsuite/frc-docs/issues/1869

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
